#! /bin/sh

#xrandr --output DP-2 --auto --primary
#xrandr --output HDMI-0 --auto --left-of DP-2

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/xfce-polkit/xfce-polkit &
sxhkd &

picom -f &

nm-applet &
xfce4-power-manager & 
#pamac-tray
#clipit &
blueman-applet &

nextcloud &

bspc monitor -d I II III IV V
#bspc monitor DP-2 -d I II III IV
#bspc monitor HDMI-0 -d V VI
#bspc wm -O DP-2 HDMI-0

feh --bg-fill ~/Pictures/Wallpapers/65757.jpg &

# REPLACE THE BAR
$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap           12

bspc config active_border_color \#bd93f9
bspc config normal_border_color \#6272a4
bspc config focused_border_color \#bd93f9

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# THESE SHOULD PROBABLY BE CHANGED...
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
